# this is the build file for project chisel
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

AS=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
MM=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CU=/usr/bin/clang
CXX=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
MXX=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
SC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend

LD=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
SCLD=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc
AR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar
SH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
SCSH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc

Programm_LD=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
Programm_CXX=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
Programm_CXX=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
Programm_CXX=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
chisel_tl_AR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar
chisel_tl_CXX=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
chisel_tl_CXX=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
chisel_tl_CXX=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++

Programm_CXXFLAGS=-Qunused-arguments -target x86_64-apple-macos15.5 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk -g -O0 -std=c++20 -Isrc/include/chisel
Programm_CXXFLAGS=
Programm_CXXFLAGS=
Programm_LDFLAGS=-target x86_64-apple-macos15.5 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk -lz -Lbuild/macosx/x86_64/debug -lchisel_tl
chisel_tl_CXXFLAGS=-Qunused-arguments -target x86_64-apple-macos15.5 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk -g -O0 -std=c++20 -Isrc/include/chisel -Isrc/ctd
chisel_tl_CXXFLAGS=
chisel_tl_CXXFLAGS=
chisel_tl_ARFLAGS=-cr

default:  Programm chisel_tl

all:  Programm chisel_tl

.PHONY: default all  Programm chisel_tl

Programm: build/macosx/x86_64/debug/Programm
build/macosx/x86_64/debug/Programm: build/macosx/x86_64/debug/libchisel_tl.a build/.objs/Programm/macosx/x86_64/debug/src/main.cpp.o
	@echo linking.debug Programm
	@mkdir -p build/macosx/x86_64/debug
	$(VV)$(Programm_LD) -o build/macosx/x86_64/debug/Programm build/.objs/Programm/macosx/x86_64/debug/src/main.cpp.o $(Programm_LDFLAGS)

build/.objs/Programm/macosx/x86_64/debug/src/main.cpp.o: src/main.cpp
	@echo compiling.debug src/main.cpp
	@mkdir -p build/.objs/Programm/macosx/x86_64/debug/src
	$(VV)$(Programm_CXX) -c $(Programm_CXXFLAGS) -o build/.objs/Programm/macosx/x86_64/debug/src/main.cpp.o src/main.cpp

chisel_tl: build/macosx/x86_64/debug/libchisel_tl.a
build/macosx/x86_64/debug/libchisel_tl.a: build/.objs/chisel_tl/macosx/x86_64/debug/src/ctd/String.cpp.o build/.objs/chisel_tl/macosx/x86_64/debug/src/ctd/new.cpp.o
	@echo linking.debug libchisel_tl.a
	@mkdir -p build/macosx/x86_64/debug
	$(VV)$(chisel_tl_AR) $(chisel_tl_ARFLAGS) build/macosx/x86_64/debug/libchisel_tl.a build/.objs/chisel_tl/macosx/x86_64/debug/src/ctd/String.cpp.o build/.objs/chisel_tl/macosx/x86_64/debug/src/ctd/new.cpp.o

build/.objs/chisel_tl/macosx/x86_64/debug/src/ctd/String.cpp.o: src/ctd/String.cpp
	@echo compiling.debug src/ctd/String.cpp
	@mkdir -p build/.objs/chisel_tl/macosx/x86_64/debug/src/ctd
	$(VV)$(chisel_tl_CXX) -c $(chisel_tl_CXXFLAGS) -o build/.objs/chisel_tl/macosx/x86_64/debug/src/ctd/String.cpp.o src/ctd/String.cpp

build/.objs/chisel_tl/macosx/x86_64/debug/src/ctd/new.cpp.o: src/ctd/new.cpp
	@echo compiling.debug src/ctd/new.cpp
	@mkdir -p build/.objs/chisel_tl/macosx/x86_64/debug/src/ctd
	$(VV)$(chisel_tl_CXX) -c $(chisel_tl_CXXFLAGS) -o build/.objs/chisel_tl/macosx/x86_64/debug/src/ctd/new.cpp.o src/ctd/new.cpp

clean:  clean_Programm clean_chisel_tl

clean_Programm:  clean_chisel_tl
	@rm -rf build/macosx/x86_64/debug/Programm
	@rm -rf build/macosx/x86_64/debug/Programm.dSYM
	@rm -rf build/.objs/Programm/macosx/x86_64/debug/src/main.cpp.o

clean_chisel_tl: 
	@rm -rf build/macosx/x86_64/debug/libchisel_tl.a
	@rm -rf build/macosx/x86_64/debug/chisel_tl.dSYM
	@rm -rf build/.objs/chisel_tl/macosx/x86_64/debug/src/ctd/String.cpp.o
	@rm -rf build/.objs/chisel_tl/macosx/x86_64/debug/src/ctd/new.cpp.o

